### ISSUE TITLE
The impacts values are not working

### ISSUE THREAD

**Issue by martingaldeca** [genai-impact/ecologits.js#8]
I was working with the documentation example from the [npm package](https://www.npmjs.com/package/@genai-impact/ecologits-openai?activeTab=readme). And I'm receiving always the same answer in the values: `undefined`.

The call to openai is working, as I can see the response in the logs `response.choices[0].message.content`

Do you know why this is happening?

Thanks in advance!
![code](https://github.com/user-attachments/assets/bedf428c-3353-4701-bab4-11438f89dec8)
![Output](https://github.com/user-attachments/assets/50930511-a2ea-4047-a476-566145064887)

**Comment by ycouble** [comment]
Hello !
Thanks for reporting, there was indeed a broken reference to the model data.
It has been fixed in v4.49.8 and published on npm.
Upgrade your version and it should be fixed. If not, please come again to report it.
Cheers

**Comment by martingaldeca** [comment]
> Hello ! Thanks for reporting, there was indeed a broken reference to the model data. It has been fixed in v4.49.8 and published on npm. Upgrade your version and it should be fixed. If not, please come again to report it. Cheers

Yes! Now it is working! Thank you very much for your fast response!
